### ISSUE TITLE
--read-buffer-size-bytes option seems not working

### ISSUE THREAD

**Issue by AlexGogin** [abstracta/wiresham#1]
I exported json from Wireshark and try to get wiresharm running. 
It always gives me the same error, doesn't matter what I put to -b or --read-buffer-size-bytes option. 

c:\myfolder>java -jar wiresham-0.2.1-standalone.jar --read-buffer-size-bytes 4096 -p 2324 -w 0.0.0.0 wireshark_export.json
Exception in thread "main" java.lang.IllegalArgumentException: Read buffer size of 2048 bytes is not enough for receiving expected packet from client with

**Comment by rabelenda** [comment]
Thank you for reporting the bug, we really appreciate it!

We have released https://github.com/abstracta/wiresham/releases/tag/v0.2.2 which should fix reported bug. Please let us know if this solves your problem.

If you find the tool helpful, please feel free to leave an star in the repo.

Regards.

**Comment by AlexGogin** [comment]
Yep. It works now. Thank you! 
Actually I already work around it by changing the buffer size in source code and recompile it =)
